project:
  type: book
  output-dir: docs

book:
  title: "Writing Reproducible Journal Articles using Rmarkdown"
  author: "Taro Mieno"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 1_WORD.qmd
    - 2_PDF-Rmarkdown.qmd
    - 3_PDF-Quarto.qmd
    - 4_PDF-KnitrLatex.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
# filters:
#   - quarto
#   - line-highlight
editor: visual

