project:
  type: book
  output-dir: docs

book:
  title: "Reproducible Journal Articles using R with Rmarkdown/Quarto"
  author: "Taro Mieno"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - text: "---"
    - part: "Reproducible Research"
      chapters:
        - C0_0_ReproducibleResearch.qmd
    - text: "---"
    - part: "Project Setup"
      chapters:
        - C1_0_IntroProject.qmd
        - C1_1_ProjectOrganization.qmd
        - C1_2_DevelopProject.qmd
        - C1_3_VersionControl.qmd
    - text: "---"
    - part: "Manuscript Writing"
      chapters:
        - C2_1_IntroWriting.qmd
        - C2_2_Rmarkdown_WORD.qmd
        - C2_3_Rmarkdown_PDF.qmd
        - C2_4_Quarto_PDF.qmd
        - C2_5_KnitrLatex_PDF.qmd
    - text: "---"
    - part: "References"
      chapters:
        - C_End_References.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
# filters:
#   - quarto
#   - line-highlight
editor: visual

