project:
  type: book
  output-dir: docs

book:
  title: "Reproducible Research Projects and Journal Articles with R"
  author: "Taro Mieno"
  date: today
  chapters:
    - index.qmd
    - text: "---"
    - part: "Reproducible Research"
      chapters:
        - C0_0_ReproducibleResearch.qmd
    - text: "---"
    - part: "Project Setup"
      chapters:
        - C1_1_ProjectOrganization.qmd
        - C1_2_DevelopProject.qmd
        - C1_3_VersionControl.qmd
    - text: "---"
    - part: "Manuscript Writing"
      chapters:
        - C2_1_IntroWriting.qmd
        - C2_2_Rmarkdown_WORD.qmd
        - C2_3_Rmarkdown_PDF.qmd
        - C2_4_Quarto_PDF.qmd
        # - C2_5_KnitrLatex_PDF.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-in-header:
      - analytics.html
    callout-icon: false

# filters:
#   - quarto
#   - line-highlight
editor: visual

